services:
  - type: web
    name: backend-app
    env: docker
    plan: free
    dockerContext: ./Ecomm-Backend
    dockerfilePath: ./Ecomm-Backend/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://hopper.proxy.rlwy.net:49127/railway?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: <your-railway-password>
      - key: SERVER_PORT
        value: 9090
      - key: JWT_KEY_SECRET
        value: A_Very_Unique_And_Strong_Secret_Key_For_Your_Project_123456789
      - key: RAZORPAY_KEYID
        value: rzp_test_RF6hzq0v3uw8Ej
      - key: RAZORPAY_KEYSECRET
        value: PdrDVnYTDOqskKF6IIhh7ACs
